# ===============================
# Application
# ===============================
spring.application.name=ProductMS

# ===============================
# MongoDB Configuration
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/rms

# ===============================
# Logging Configuration
# ===============================
# Spring Data MongoDB
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository.query=DEBUG
# MongoDB Driver (Logs actual MongoDB commands)
logging.level.org.mongodb.driver.protocol.command=TRACE
# Optional Driver Logs
logging.level.org.mongodb.driver.connection=INFO
logging.level.org.mongodb.driver.cluster=INFO

# ===============================
# Server Configuration (Optional)
# ===============================
server.port=8080